//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Vida.View.Agendamento.RelatoriosCrystal {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DSRelatorioSolicitacaoAmbulatorial")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DSRelatorioSolicitacaoAmbulatorial : global::System.Data.DataSet {
        
        private RelatorioSolicitacaoDataTable tableRelatorioSolicitacao;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DSRelatorioSolicitacaoAmbulatorial() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DSRelatorioSolicitacaoAmbulatorial(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["RelatorioSolicitacao"] != null)) {
                    base.Tables.Add(new RelatorioSolicitacaoDataTable(ds.Tables["RelatorioSolicitacao"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public RelatorioSolicitacaoDataTable RelatorioSolicitacao {
            get {
                return this.tableRelatorioSolicitacao;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            DSRelatorioSolicitacaoAmbulatorial cln = ((DSRelatorioSolicitacaoAmbulatorial)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["RelatorioSolicitacao"] != null)) {
                    base.Tables.Add(new RelatorioSolicitacaoDataTable(ds.Tables["RelatorioSolicitacao"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableRelatorioSolicitacao = ((RelatorioSolicitacaoDataTable)(base.Tables["RelatorioSolicitacao"]));
            if ((initTable == true)) {
                if ((this.tableRelatorioSolicitacao != null)) {
                    this.tableRelatorioSolicitacao.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DSRelatorioSolicitacaoAmbulatorial";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DSRelatorioSolicitacaoAmbulatorial.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableRelatorioSolicitacao = new RelatorioSolicitacaoDataTable();
            base.Tables.Add(this.tableRelatorioSolicitacao);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeRelatorioSolicitacao() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DSRelatorioSolicitacaoAmbulatorial ds = new DSRelatorioSolicitacaoAmbulatorial();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void RelatorioSolicitacaoRowChangeEventHandler(object sender, RelatorioSolicitacaoRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class RelatorioSolicitacaoDataTable : global::System.Data.TypedTableBase<RelatorioSolicitacaoRow> {
            
            private global::System.Data.DataColumn columnDataSolicitacao;
            
            private global::System.Data.DataColumn columnUsuarioSolicitante;
            
            private global::System.Data.DataColumn columnUnidadeSolicitante;
            
            private global::System.Data.DataColumn columnCNS;
            
            private global::System.Data.DataColumn columnNomePaciente;
            
            private global::System.Data.DataColumn columnProcedimento;
            
            private global::System.Data.DataColumn columnUnidadeExecutante;
            
            private global::System.Data.DataColumn columnTurno;
            
            private global::System.Data.DataColumn columnSituacao;
            
            private global::System.Data.DataColumn columnDataAgenda;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RelatorioSolicitacaoDataTable() {
                this.TableName = "RelatorioSolicitacao";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal RelatorioSolicitacaoDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected RelatorioSolicitacaoDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DataSolicitacaoColumn {
                get {
                    return this.columnDataSolicitacao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn UsuarioSolicitanteColumn {
                get {
                    return this.columnUsuarioSolicitante;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn UnidadeSolicitanteColumn {
                get {
                    return this.columnUnidadeSolicitante;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CNSColumn {
                get {
                    return this.columnCNS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NomePacienteColumn {
                get {
                    return this.columnNomePaciente;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ProcedimentoColumn {
                get {
                    return this.columnProcedimento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn UnidadeExecutanteColumn {
                get {
                    return this.columnUnidadeExecutante;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TurnoColumn {
                get {
                    return this.columnTurno;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SituacaoColumn {
                get {
                    return this.columnSituacao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DataAgendaColumn {
                get {
                    return this.columnDataAgenda;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RelatorioSolicitacaoRow this[int index] {
                get {
                    return ((RelatorioSolicitacaoRow)(this.Rows[index]));
                }
            }
            
            public event RelatorioSolicitacaoRowChangeEventHandler RelatorioSolicitacaoRowChanging;
            
            public event RelatorioSolicitacaoRowChangeEventHandler RelatorioSolicitacaoRowChanged;
            
            public event RelatorioSolicitacaoRowChangeEventHandler RelatorioSolicitacaoRowDeleting;
            
            public event RelatorioSolicitacaoRowChangeEventHandler RelatorioSolicitacaoRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddRelatorioSolicitacaoRow(RelatorioSolicitacaoRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RelatorioSolicitacaoRow AddRelatorioSolicitacaoRow(string DataSolicitacao, string UsuarioSolicitante, string UnidadeSolicitante, string CNS, string NomePaciente, string Procedimento, string UnidadeExecutante, string Turno, string Situacao, string DataAgenda) {
                RelatorioSolicitacaoRow rowRelatorioSolicitacaoRow = ((RelatorioSolicitacaoRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        DataSolicitacao,
                        UsuarioSolicitante,
                        UnidadeSolicitante,
                        CNS,
                        NomePaciente,
                        Procedimento,
                        UnidadeExecutante,
                        Turno,
                        Situacao,
                        DataAgenda};
                rowRelatorioSolicitacaoRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowRelatorioSolicitacaoRow);
                return rowRelatorioSolicitacaoRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                RelatorioSolicitacaoDataTable cln = ((RelatorioSolicitacaoDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new RelatorioSolicitacaoDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnDataSolicitacao = base.Columns["DataSolicitacao"];
                this.columnUsuarioSolicitante = base.Columns["UsuarioSolicitante"];
                this.columnUnidadeSolicitante = base.Columns["UnidadeSolicitante"];
                this.columnCNS = base.Columns["CNS"];
                this.columnNomePaciente = base.Columns["NomePaciente"];
                this.columnProcedimento = base.Columns["Procedimento"];
                this.columnUnidadeExecutante = base.Columns["UnidadeExecutante"];
                this.columnTurno = base.Columns["Turno"];
                this.columnSituacao = base.Columns["Situacao"];
                this.columnDataAgenda = base.Columns["DataAgenda"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnDataSolicitacao = new global::System.Data.DataColumn("DataSolicitacao", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataSolicitacao);
                this.columnUsuarioSolicitante = new global::System.Data.DataColumn("UsuarioSolicitante", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUsuarioSolicitante);
                this.columnUnidadeSolicitante = new global::System.Data.DataColumn("UnidadeSolicitante", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUnidadeSolicitante);
                this.columnCNS = new global::System.Data.DataColumn("CNS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCNS);
                this.columnNomePaciente = new global::System.Data.DataColumn("NomePaciente", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNomePaciente);
                this.columnProcedimento = new global::System.Data.DataColumn("Procedimento", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnProcedimento);
                this.columnUnidadeExecutante = new global::System.Data.DataColumn("UnidadeExecutante", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUnidadeExecutante);
                this.columnTurno = new global::System.Data.DataColumn("Turno", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTurno);
                this.columnSituacao = new global::System.Data.DataColumn("Situacao", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSituacao);
                this.columnDataAgenda = new global::System.Data.DataColumn("DataAgenda", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDataAgenda);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RelatorioSolicitacaoRow NewRelatorioSolicitacaoRow() {
                return ((RelatorioSolicitacaoRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new RelatorioSolicitacaoRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(RelatorioSolicitacaoRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RelatorioSolicitacaoRowChanged != null)) {
                    this.RelatorioSolicitacaoRowChanged(this, new RelatorioSolicitacaoRowChangeEvent(((RelatorioSolicitacaoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RelatorioSolicitacaoRowChanging != null)) {
                    this.RelatorioSolicitacaoRowChanging(this, new RelatorioSolicitacaoRowChangeEvent(((RelatorioSolicitacaoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RelatorioSolicitacaoRowDeleted != null)) {
                    this.RelatorioSolicitacaoRowDeleted(this, new RelatorioSolicitacaoRowChangeEvent(((RelatorioSolicitacaoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RelatorioSolicitacaoRowDeleting != null)) {
                    this.RelatorioSolicitacaoRowDeleting(this, new RelatorioSolicitacaoRowChangeEvent(((RelatorioSolicitacaoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveRelatorioSolicitacaoRow(RelatorioSolicitacaoRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DSRelatorioSolicitacaoAmbulatorial ds = new DSRelatorioSolicitacaoAmbulatorial();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "RelatorioSolicitacaoDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class RelatorioSolicitacaoRow : global::System.Data.DataRow {
            
            private RelatorioSolicitacaoDataTable tableRelatorioSolicitacao;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal RelatorioSolicitacaoRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRelatorioSolicitacao = ((RelatorioSolicitacaoDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DataSolicitacao {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioSolicitacao.DataSolicitacaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DataSolicitacao\' in table \'RelatorioSolicitacao\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableRelatorioSolicitacao.DataSolicitacaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string UsuarioSolicitante {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioSolicitacao.UsuarioSolicitanteColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UsuarioSolicitante\' in table \'RelatorioSolicitacao\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableRelatorioSolicitacao.UsuarioSolicitanteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string UnidadeSolicitante {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioSolicitacao.UnidadeSolicitanteColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UnidadeSolicitante\' in table \'RelatorioSolicitacao\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableRelatorioSolicitacao.UnidadeSolicitanteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CNS {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioSolicitacao.CNSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CNS\' in table \'RelatorioSolicitacao\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioSolicitacao.CNSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NomePaciente {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioSolicitacao.NomePacienteColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NomePaciente\' in table \'RelatorioSolicitacao\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioSolicitacao.NomePacienteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Procedimento {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioSolicitacao.ProcedimentoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Procedimento\' in table \'RelatorioSolicitacao\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioSolicitacao.ProcedimentoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string UnidadeExecutante {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioSolicitacao.UnidadeExecutanteColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UnidadeExecutante\' in table \'RelatorioSolicitacao\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableRelatorioSolicitacao.UnidadeExecutanteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Turno {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioSolicitacao.TurnoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Turno\' in table \'RelatorioSolicitacao\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioSolicitacao.TurnoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Situacao {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioSolicitacao.SituacaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Situacao\' in table \'RelatorioSolicitacao\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioSolicitacao.SituacaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DataAgenda {
                get {
                    try {
                        return ((string)(this[this.tableRelatorioSolicitacao.DataAgendaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DataAgenda\' in table \'RelatorioSolicitacao\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRelatorioSolicitacao.DataAgendaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDataSolicitacaoNull() {
                return this.IsNull(this.tableRelatorioSolicitacao.DataSolicitacaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDataSolicitacaoNull() {
                this[this.tableRelatorioSolicitacao.DataSolicitacaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsUsuarioSolicitanteNull() {
                return this.IsNull(this.tableRelatorioSolicitacao.UsuarioSolicitanteColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetUsuarioSolicitanteNull() {
                this[this.tableRelatorioSolicitacao.UsuarioSolicitanteColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsUnidadeSolicitanteNull() {
                return this.IsNull(this.tableRelatorioSolicitacao.UnidadeSolicitanteColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetUnidadeSolicitanteNull() {
                this[this.tableRelatorioSolicitacao.UnidadeSolicitanteColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCNSNull() {
                return this.IsNull(this.tableRelatorioSolicitacao.CNSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCNSNull() {
                this[this.tableRelatorioSolicitacao.CNSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNomePacienteNull() {
                return this.IsNull(this.tableRelatorioSolicitacao.NomePacienteColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNomePacienteNull() {
                this[this.tableRelatorioSolicitacao.NomePacienteColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsProcedimentoNull() {
                return this.IsNull(this.tableRelatorioSolicitacao.ProcedimentoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetProcedimentoNull() {
                this[this.tableRelatorioSolicitacao.ProcedimentoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsUnidadeExecutanteNull() {
                return this.IsNull(this.tableRelatorioSolicitacao.UnidadeExecutanteColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetUnidadeExecutanteNull() {
                this[this.tableRelatorioSolicitacao.UnidadeExecutanteColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTurnoNull() {
                return this.IsNull(this.tableRelatorioSolicitacao.TurnoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTurnoNull() {
                this[this.tableRelatorioSolicitacao.TurnoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSituacaoNull() {
                return this.IsNull(this.tableRelatorioSolicitacao.SituacaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSituacaoNull() {
                this[this.tableRelatorioSolicitacao.SituacaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDataAgendaNull() {
                return this.IsNull(this.tableRelatorioSolicitacao.DataAgendaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDataAgendaNull() {
                this[this.tableRelatorioSolicitacao.DataAgendaColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class RelatorioSolicitacaoRowChangeEvent : global::System.EventArgs {
            
            private RelatorioSolicitacaoRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RelatorioSolicitacaoRowChangeEvent(RelatorioSolicitacaoRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RelatorioSolicitacaoRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591